import { Cookie, Inter } from 'next/font/google';
// import styles from '@/styles/Main.module.scss'
import Head from 'next/head';
import Hero from '@/components/Hero'
import AboutSEO from '@/components/AboutSEO';
import Services from '@/components/Services';
import Agency from '@/components/Agency';
import How from '@/components/HowWeWork';
import Contact from '@/Navigation/Contact';
import Cookies from '@/Navigation/Cookie';
// import Policy from '@/pages/privacyPolicy';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>SEO Rocket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <div className='all'>
        <Cookies />
        <Hero/>
        <AboutSEO/>
        <Services />
        <Agency />
        <How />
        <Contact />
      </div>
    </div>
  )
}
